os: linux
dist: xenial
language: node_js
node_js:
- '11'
cache:
  # cache for ci, since it deletes node_modules
  directories:
  - "$HOME/.npm"
before_install:
- openssl aes-256-cbc -K $encrypted_163f8f7b49e8_key -iv $encrypted_163f8f7b49e8_iv
  -in travis-key.enc -out travis-key -d
- sudo apt-get update
- sudo apt-get install git-crypt
- git-crypt unlock travis-key
install:
- npm run installFromLock
script: npm run preCommit
