os: linux
dist: xenial
language: node_js
node_js:
- '11'
cache:
  # cache for ci, since it deletes node_modules
  directories:
  - "$HOME/.npm"
before_install:
- openssl aes-256-cbc -K $encrypted_163f8f7b49e8_key -iv $encrypted_163f8f7b49e8_iv
  -in travis-key.enc -out travis-key -d
- sudo apt-get update
- sudo apt-get install git-crypt
- git-crypt unlock travis-key
install:
- npm run installFromLock
# we are running a separate script from preCommmit for the
# moment because we don't yet support installation and configuration
# of prisma and DB on Travis.
# so instead we are still just running the old preCommit script, but
# with a different name sice we **do** support e2e on developer pre-commit
script: npm run ci-lint-and-test
